
export const countries = [
  { name: "Afghanistan", code: "+93", iso: "AF", length: 9 },
  { name: "Albania", code: "+355", iso: "AL", length: 9 },
  { name: "Algeria", code: "+213", iso: "DZ", length: 9 },
  { name: "American Samoa", code: "+1-684", iso: "AS", length: 10 },
  { name: "Andorra", code: "+376", iso: "AD", length: 6 },
  { name: "Angola", code: "+244", iso: "AO", length: 9 },
  { name: "Anguilla", code: "+1-264", iso: "AI", length: 10 },
  { name: "Antigua and Barbuda", code: "+1-268", iso: "AG", length: 10 },
  { name: "Argentina", code: "+54", iso: "AR", length: 10 },
  { name: "Armenia", code: "+374", iso: "AM", length: 8 },
  { name: "Aruba", code: "+297", iso: "AW", length: 7 },
  { name: "Australia", code: "+61-AU", iso: "AU", length: 9 },
  { name: "Austria", code: "+43", iso: "AT", length: 10 },
  { name: "Azerbaijan", code: "+994", iso: "AZ", length: 9 },
  { name: "Bahamas", code: "+1-242", iso: "BS", length: 10 },
  { name: "Bahrain", code: "+973", iso: "BH", length: 8 },
  { name: "Bangladesh", code: "+880", iso: "BD", length: 10 },
  { name: "Barbados", code: "+1-246", iso: "BB", length: 10 },
  { name: "Belarus", code: "+375", iso: "BY", length: 9 },
  { name: "Belgium", code: "+32", iso: "BE", length: 9 },
  { name: "Belize", code: "+501", iso: "BZ", length: 7 },
  { name: "Benin", code: "+229", iso: "BJ", length: 8 },
  { name: "Bermuda", code: "+1-441", iso: "BM", length: 10 },
  { name: "Bhutan", code: "+975", iso: "BT", length: 8 },
  { name: "Bolivia", code: "+591", iso: "BO", length: 8 },
  { name: "Bosnia and Herzegovina", code: "+387", iso: "BA", length: 8 },
  { name: "Botswana", code: "+267", iso: "BW", length: 8 },
  { name: "Brazil", code: "+55", iso: "BR", length: 11 },
  { name: "British Indian Ocean Territory", code: "+246", iso: "IO", length: 7 },
  { name: "British Virgin Islands", code: "+1-284", iso: "VG", length: 10 },
  { name: "Brunei", code: "+673", iso: "BN", length: 7 },
  { name: "Bulgaria", code: "+359", iso: "BG", length: 9 },
  { name: "Burkina Faso", code: "+226", iso: "BF", length: 8 },
  { name: "Burundi", code: "+257", iso: "BI", length: 8 },
  { name: "Cambodia", code: "+855", iso: "KH", length: 9 },
  { name: "Cameroon", code: "+237", iso: "CM", length: 9 },
  { name: "Canada", code: "+1-CA", iso: "CA", length: 10 },
  { name: "Cape Verde", code: "+238", iso: "CV", length: 7 },
  { name: "Cayman Islands", code: "+1-345", iso: "KY", length: 10 },
  { name: "Central African Republic", code: "+236", iso: "CF", length: 8 },
  { name: "Chad", code: "+235", iso: "TD", length: 8 },
  { name: "Chile", code: "+56", iso: "CL", length: 9 },
  { name: "China", code: "+86", iso: "CN", length: 11 },
  { name: "Christmas Island", code: "+61-CX", iso: "CX", length: 9 },
  { name: "Cocos Islands", code: "+61-CC", iso: "CC", length: 9 },
  { name: "Colombia", code: "+57", iso: "CO", length: 10 },
  { name: "Comoros", code: "+269", iso: "KM", length: 7 },
  { name: "Cook Islands", code: "+682", iso: "CK", length: 5 },
  { name: "Costa Rica", code: "+506", iso: "CR", length: 8 },
  { name: "Croatia", code: "+385", iso: "HR", length: 9 },
  { name: "Cuba", code: "+53", iso: "CU", length: 8 },
  { name: "Curacao", code: "+599-CW", iso: "CW", length: 7 },
  { name: "Cyprus", code: "+357", iso: "CY", length: 8 },
  { name: "Czech Republic", code: "+420", iso: "CZ", length: 9 },
  { name: "Democratic Republic of the Congo", code: "+243", iso: "CD", length: 9 },
  { name: "Denmark", code: "+45", iso: "DK", length: 8 },
  { name: "Djibouti", code: "+253", iso: "DJ", length: 6 },
  { name: "Dominica", code: "+1-767", iso: "DM", length: 10 },
  { name: "Dominican Republic", code: "+1-809", iso: "DO", length: 10 }, // Assuming 809 is primary
  { name: "East Timor", code: "+670", iso: "TL", length: 8 },
  { name: "Ecuador", code: "+593", iso: "EC", length: 9 },
  { name: "Egypt", code: "+20", iso: "EG", length: 10 },
  { name: "El Salvador", code: "+503", iso: "SV", length: 8 },
  { name: "Equatorial Guinea", code: "+240", iso: "GQ", length: 9 },
  { name: "Eritrea", code: "+291", iso: "ER", length: 7 },
  { name: "Estonia", code: "+372", iso: "EE", length: 8 },
  { name: "Ethiopia", code: "+251", iso: "ET", length: 9 },
  { name: "Falkland Islands", code: "+500", iso: "FK", length: 5 },
  { name: "Faroe Islands", code: "+298", iso: "FO", length: 6 },
  { name: "Fiji", code: "+679", iso: "FJ", length: 7 },
  { name: "Finland", code: "+358", iso: "FI", length: 10 },
  { name: "France", code: "+33", iso: "FR", length: 9 },
  { name: "French Polynesia", code: "+689", iso: "PF", length: 6 },
  { name: "Gabon", code: "+241", iso: "GA", length: 8 },
  { name: "Gambia", code: "+220", iso: "GM", length: 7 },
  { name: "Georgia", code: "+995", iso: "GE", length: 9 },
  { name: "Germany", code: "+49", iso: "DE", length: 11 },
  { name: "Ghana", code: "+233", iso: "GH", length: 9 },
  { name: "Gibraltar", code: "+350", iso: "GI", length: 8 },
  { name: "Greece", code: "+30", iso: "GR", length: 10 },
  { name: "Greenland", code: "+299", iso: "GL", length: 6 },
  { name: "Grenada", code: "+1-473", iso: "GD", length: 10 },
  { name: "Guam", code: "+1-671", iso: "GU", length: 10 },
  { name: "Guatemala", code: "+502", iso: "GT", length: 8 },
  { name: "Guernsey", code: "+44-GG", iso: "GG", length: 10 },
  { name: "Guinea", code: "+224", iso: "GN", length: 9 },
  { name: "Guinea-Bissau", code: "+245", iso: "GW", length: 7 },
  { name: "Guyana", code: "+592", iso: "GY", length: 7 },
  { name: "Haiti", code: "+509", iso: "HT", length: 8 },
  { name: "Honduras", code: "+504", iso: "HN", length: 8 },
  { name: "Hong Kong", code: "+852", iso: "HK", length: 8 },
  { name: "Hungary", code: "+36", iso: "HU", length: 9 },
  { name: "Iceland", code: "+354", iso: "IS", length: 7 },
  { name: "India", code: "+91", iso: "IN", length: 10 },
  { name: "Indonesia", code: "+62", iso: "ID", length: 10 },
  { name: "Iran", code: "+98", iso: "IR", length: 10 },
  { name: "Iraq", code: "+964", iso: "IQ", length: 10 },
  { name: "Ireland", code: "+353", iso: "IE", length: 9 },
  { name: "Isle of Man", code: "+44-IM", iso: "IM", length: 10 },
  { name: "Israel", code: "+972", iso: "IL", length: 9 },
  { name: "Italy", code: "+39", iso: "IT", length: 10 },
  { name: "Ivory Coast", code: "+225", iso: "CI", length: 8 },
  { name: "Jamaica", code: "+1-876", iso: "JM", length: 10 },
  { name: "Japan", code: "+81", iso: "JP", length: 10 },
  { name: "Jersey", code: "+44-JE", iso: "JE", length: 10 },
  { name: "Jordan", code: "+962", iso: "JO", length: 9 },
  { name: "Kazakhstan", code: "+7-KZ", iso: "KZ", length: 10 },
  { name: "Kenya", code: "+254", iso: "KE", length: 9 },
  { name: "Kiribati", code: "+686", iso: "KI", length: 5 },
  { name: "Kosovo", code: "+383", iso: "XK", length: 8 },
  { name: "Kuwait", code: "+965", iso: "KW", length: 8 },
  { name: "Kyrgyzstan", code: "+996", iso: "KG", length: 9 },
  { name: "Laos", code: "+856", iso: "LA", length: 8 },
  { name: "Latvia", code: "+371", iso: "LV", length: 8 },
  { name: "Lebanon", code: "+961", iso: "LB", length: 8 },
  { name: "Lesotho", code: "+266", iso: "LS", length: 8 },
  { name: "Liberia", code: "+231", iso: "LR", length: 7 },
  { name: "Libya", code: "+218", iso: "LY", length: 9 },
  { name: "Liechtenstein", code: "+423", iso: "LI", length: 7 },
  { name: "Lithuania", code: "+370", iso: "LT", length: 8 },
  { name: "Luxembourg", code: "+352", iso: "LU", length: 9 },
  { name: "Macau", code: "+853", iso: "MO", length: 8 },
  { name: "Macedonia", code: "+389", iso: "MK", length: 8 },
  { name: "Madagascar", code: "+261", iso: "MG", length: 9 },
  { name: "Malawi", code: "+265", iso: "MW", length: 9 },
  { name: "Malaysia", code: "+60", iso: "MY", length: 9 },
  { name: "Maldives", code: "+960", iso: "MV", length: 7 },
  { name: "Mali", code: "+223", iso: "ML", length: 8 },
  { name: "Malta", code: "+356", iso: "MT", length: 8 },
  { name: "Marshall Islands", code: "+692", iso: "MH", length: 7 },
  { name: "Mauritania", code: "+222", iso: "MR", length: 8 },
  { name: "Mauritius", code: "+230", iso: "MU", length: 8 },
  { name: "Mayotte", code: "+262-YT", iso: "YT", length: 9 },
  { name: "Mexico", code: "+52", iso: "MX", length: 10 },
  { name: "Micronesia", code: "+691", iso: "FM", length: 7 },
  { name: "Moldova", code: "+373", iso: "MD", length: 8 },
  { name: "Monaco", code: "+377", iso: "MC", length: 8 },
  { name: "Mongolia", code: "+976", iso: "MN", length: 8 },
  { name: "Montenegro", code: "+382", iso: "ME", length: 8 },
  { name: "Montserrat", code: "+1-664", iso: "MS", length: 10 },
  { name: "Morocco", code: "+212", iso: "MA", length: 9 },
  { name: "Mozambique", code: "+258", iso: "MZ", length: 9 },
  { name: "Myanmar", code: "+95", iso: "MM", length: 8 },
  { name: "Namibia", code: "+264", iso: "NA", length: 9 },
  { name: "Nauru", code: "+674", iso: "NR", length: 7 },
  { name: "Nepal", code: "+977", iso: "NP", length: 10 },
  { name: "Netherlands", code: "+31", iso: "NL", length: 9 },
  { name: "Netherlands Antilles", code: "+599-AN", iso: "AN", length: 7 },
  { name: "New Caledonia", code: "+687", iso: "NC", length: 6 },
  { name: "New Zealand", code: "+64", iso: "NZ", length: 9 },
  { name: "Nicaragua", code: "+505", iso: "NI", length: 8 },
  { name: "Niger", code: "+227", iso: "NE", length: 8 },
  { name: "Nigeria", code: "+234", iso: "NG", length: 10 },
  { name: "Niue", code: "+683", iso: "NU", length: 4 },
  { name: "Northern Mariana Islands", code: "+1-670", iso: "MP", length: 10 },
  { name: "North Korea", code: "+850", iso: "KP", length: 10 },
  { name: "Norway", code: "+47-NO", iso: "NO", length: 8 },
  { name: "Oman", code: "+968", iso: "OM", length: 8 },
  { name: "Pakistan", code: "+92", iso: "PK", length: 10 },
  { name: "Palau", code: "+680", iso: "PW", length: 7 },
  { name: "Palestine", code: "+970", iso: "PS", length: 9 },
  { name: "Panama", code: "+507", iso: "PA", length: 8 },
  { name: "Papua New Guinea", code: "+675", iso: "PG", length: 8 },
  { name: "Paraguay", code: "+595", iso: "PY", length: 9 },
  { name: "Peru", code: "+51", iso: "PE", length: 9 },
  { name: "Philippines", code: "+63", iso: "PH", length: 10 },
  { name: "Pitcairn", code: "+64-PN", iso: "PN", length: 9 },
  { name: "Poland", code: "+48", iso: "PL", length: 9 },
  { name: "Portugal", code: "+351", iso: "PT", length: 9 },
  { name: "Puerto Rico", code: "+1-PR", iso: "PR", length: 10 }, // Simplified
  { name: "Qatar", code: "+974", iso: "QA", length: 8 },
  { name: "Republic of the Congo", code: "+242", iso: "CG", length: 9 },
  { name: "Reunion", code: "+262-RE", iso: "RE", length: 9 },
  { name: "Romania", code: "+40", iso: "RO", length: 9 },
  { name: "Russia", code: "+7-RU", iso: "RU", length: 10 },
  { name: "Rwanda", code: "+250", iso: "RW", length: 9 },
  { name: "Saint Barthelemy", code: "+590-BL", iso: "BL", length: 9 },
  { name: "Saint Helena", code: "+290", iso: "SH", length: 4 },
  { name: "Saint Kitts and Nevis", code: "+1-869", iso: "KN", length: 10 },
  { name: "Saint Lucia", code: "+1-758", iso: "LC", length: 10 },
  { name: "Saint Martin", code: "+590-MF", iso: "MF", length: 9 },
  { name: "Saint Pierre and Miquelon", code: "+508", iso: "PM", length: 6 },
  { name: "Saint Vincent and the Grenadines", code: "+1-784", iso: "VC", length: 10 },
  { name: "Samoa", code: "+685", iso: "WS", length: 7 },
  { name: "San Marino", code: "+378", iso: "SM", length: 10 },
  { name: "Sao Tome and Principe", code: "+239", iso: "ST", length: 7 },
  { name: "Saudi Arabia", code: "+966", iso: "SA", length: 9 },
  { name: "Senegal", code: "+221", iso: "SN", length: 9 },
  { name: "Serbia", code: "+381", iso: "RS", length: 9 },
  { name: "Seychelles", code: "+248", iso: "SC", length: 7 },
  { name: "Sierra Leone", code: "+232", iso: "SL", length: 8 },
  { name: "Singapore", code: "+65", iso: "SG", length: 8 },
  { name: "Sint Maarten", code: "+1-721", iso: "SX", length: 10 },
  { name: "Slovakia", code: "+421", iso: "SK", length: 9 },
  { name: "Slovenia", code: "+386", iso: "SI", length: 8 },
  { name: "Solomon Islands", code: "+677", iso: "SB", length: 7 },
  { name: "Somalia", code: "+252", iso: "SO", length: 8 },
  { name: "South Africa", code: "+27", iso: "ZA", length: 9 },
  { name: "South Korea", code: "+82", iso: "KR", length: 10 },
  { name: "South Sudan", code: "+211", iso: "SS", length: 9 },
  { name: "Spain", code: "+34", iso: "ES", length: 9 },
  { name: "Sri Lanka", code: "+94", iso: "LK", length: 9 },
  { name: "Sudan", code: "+249", iso: "SD", length: 9 },
  { name: "Suriname", code: "+597", iso: "SR", length: 7 },
  { name: "Svalbard and Jan Mayen", code: "+47-SJ", iso: "SJ", length: 8 },
  { name: "Swaziland", code: "+268", iso: "SZ", length: 8 },
  { name: "Sweden", code: "+46", iso: "SE", length: 9 },
  { name: "Switzerland", code: "+41", iso: "CH", length: 9 },
  { name: "Syria", code: "+963", iso: "SY", length: 9 },
  { name: "Taiwan", code: "+886", iso: "TW", length: 9 },
  { name: "Tajikistan", code: "+992", iso: "TJ", length: 9 },
  { name: "Tanzania", code: "+255", iso: "TZ", length: 9 },
  { name: "Thailand", code: "+66", iso: "TH", length: 9 },
  { name: "Togo", code: "+228", iso: "TG", length: 8 },
  { name: "Tokelau", code: "+690", iso: "TK", length: 4 },
  { name: "Tonga", code: "+676", iso: "TO", length: 5 },
  { name: "Trinidad and Tobago", code: "+1-868", iso: "TT", length: 10 },
  { name: "Tunisia", code: "+216", iso: "TN", length: 8 },
  { name: "Turkey", code: "+90", iso: "TR", length: 10 },
  { name: "Turkmenistan", code: "+993", iso: "TM", length: 8 },
  { name: "Turks and Caicos Islands", code: "+1-649", iso: "TC", length: 10 },
  { name: "Tuvalu", code: "+688", iso: "TV", length: 5 },
  { name: "U.S. Virgin Islands", code: "+1-340", iso: "VI", length: 10 },
  { name: "Uganda", code: "+256", iso: "UG", length: 9 },
  { name: "Ukraine", code: "+380", iso: "UA", length: 9 },
  { name: "United Arab Emirates", code: "+971", iso: "AE", length: 9 },
  { name: "United Kingdom", code: "+44-GB", iso: "GB", length: 10 },
  { name: "United States", code: "+1-US", iso: "US", length: 10 },
  { name: "Uruguay", code: "+598", iso: "UY", length: 8 },
  { name: "Uzbekistan", code: "+998", iso: "UZ", length: 9 },
  { name: "Vanuatu", code: "+678", iso: "VU", length: 7 },
  { name: "Vatican", code: "+379", iso: "VA", length: 10 },
  { name: "Venezuela", code: "+58", iso: "VE", length: 10 },
  { name: "Vietnam", code: "+84", iso: "VN", length: 9 },
  { name: "Wallis and Futuna", code: "+681", iso: "WF", length: 6 },
  { name: "Western Sahara", code: "+212-EH", iso: "EH", length: 9 },
  { name: "Yemen", code: "+967", iso: "YE", length: 9 },
  { name: "Zambia", code: "+260", iso: "ZM", length: 9 },
  { name: "Zimbabwe", code: "+263", iso: "ZW", length: 9 },
];
